[workspace]
authors = [
    "Landung 'Don' Setiawan <landungs@uw.edu>",
    "John Desanto <jdesanto@uw.edu>",
]
channels = ["conda-forge"]
name = "gnatss-workshop"
platforms = ["osx-arm64", "linux-64"]
version = "2025.08.07"

[environments]
site = ["site"]
data = ["data"]

[tasks]

[dependencies]
python = "3.11.*"
pyproj = "*"

[pypi-dependencies]
gnatss = ">=0.2.2, <0.3"

# Site feature configurations
[feature.site.pypi-dependencies]
jupyter-book = ">=2.0.0b2"


[feature.site.dependencies]
nodejs = ">=24.3.0,<24.4"

[feature.site.tasks]
start = { cmd = "jupyter book start", cwd = "docs" }
build = { cmd = "jupyter book build --html", cwd = "docs" }

[feature.site.tasks.publish]
depends-on = ["build"]
cwd = "docs"
cmd = "cp -R _build/html $READTHEDOCS_OUTPUT/html"
env = { READTHEDOCS_OUTPUT = ".." }

# Data feature configurations
[feature.data.dependencies]
typer = ">=0.16.0"
pygithub = ">=2.6.1,<3"

[feature.data.tasks]
zip = { cmd = "python data.py zip", description = "Zip the data directory" }
unzip = { cmd = "python data.py unzip", description = "Unzip data.zip to data directory" }

[feature.data.tasks.release.env]
GITHUB_REPO = "seafloor-geodesy/gnatss-workshop"

[feature.data.tasks.release]
depends-on = ["zip"]
description = "Create GitHub release with data.zip asset"
cmd = [
    "python",
    "data.py",
    "release",
    "--repo=${GITHUB_REPO}",
    "--tag=v${PIXI_PROJECT_VERSION}",
]
